name: Test Report Generator

on: [push, pull_request]

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install html2text
      
      - name: Generate HTML report
        run: python generate_report.py  # Your existing report generator
      
      - name: Convert to Markdown
        run: python html_to_md.py
      
      - name: Commit and push report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add TEST_REPORT.md
          git commit -m "Update test report [skip ci]"
          git push