name: Run Tests and Generate Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: pip install pytest pytest-html
      
      - name: Run tests and generate report
        run: python -m pytest run_tests.py --html=test_report.html --self-contained-html
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_report.html
          retention-days: 5