name: Test Report Generator

on: [push, pull_request]

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install html2text
      
      # - name: Generate HTML report
      #   run: python generate_report.py
      
      - name: Convert to Markdown
        run: python html_to_md.py
      
      - name: Commit and push report
        run: |
          git config --global user.name "amanarintech"
          git config --global user.email "aman@arintech.in"
          git add TEST_REPORT.md
          git commit -m "Update test report [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/amanarintech/Test-cases.git HEAD:main
